# Generated by Django 4.2.5 on 2023-09-14 18:50

import backend.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduleRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "schedule_json",
                    models.JSONField(default=backend.core.models.schedule_json_default, verbose_name="Schedule data"),
                ),
                (
                    "ics_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=backend.core.models.event_filepath,
                        verbose_name="Generated .ics file",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True, verbose_name="Generation date")),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("status.Queued", "Queued"),
                            ("status.InProgress", "In Progress"),
                            ("status.Ready", "Ready"),
                            ("status.Failed", "Failed"),
                        ],
                        max_length=100,
                        verbose_name="Progress status",
                    ),
                ),
                ("error", models.TextField(blank=True, max_length=200, null=True, verbose_name="Error message")),
            ],
            options={
                "verbose_name": "Schedule request",
                "verbose_name_plural": "Schedule requests",
            },
        ),
    ]
