version: "3.8"

services:
  django:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

  redis:
    image: redis:latest
